//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jarwin.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class feed_history
    {
        public long feed_id { get; set; }
        public string feed_uri { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime last_build_datetime { get; set; }
        public System.DateTime last_download_datetime { get; set; }
        public string language { get; set; }
        public Nullable<long> update_frequency { get; set; }
        public string site_uri { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public string update_period { get; set; }
        public System.DateTime archived_datetime { get; set; }
    }
}
