//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jarwin.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class feed_item
    {
        public long feed_id { get; set; }
        public long feed_item_id { get; set; }
        public string title { get; set; }
        public string item_uri { get; set; }
        public string comments { get; set; }
        public System.DateTime published_datetime { get; set; }
        public string creator { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public System.DateTime last_download_datetime { get; set; }
        public long feed_history_feed_id { get; set; }
        public System.DateTime feed_history_archived_datetime { get; set; }
    
        public virtual feed feed { get; set; }
    }
}
